function questionImageUrl(q){const value=String(q.screenshot_url||q.screenshot||'');if(!value)return '';if(/^(?:data:image\/|https?:\/\/|imported-sources\/)/i.test(value))return value;return '../Question%20Appendix/'+value.split('/').map(encodeURIComponent).join('/')}
// Keep images embedded in the HTML, but avoid copying their base64 into every DOM node.
const embeddedMediaURLs=new Map(),embeddedMediaIDs=new Map();
function embeddedMediaURL(id){if(embeddedMediaURLs.has(id))return embeddedMediaURLs.get(id);const source=DATA.assets[id];if(!source)return '';const comma=source.indexOf(','),mime=source.slice(5,source.indexOf(';')),binary=atob(source.slice(comma+1)),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:mime}));embeddedMediaURLs.set(id,url);embeddedMediaIDs.set(url,id);return url}
function resolveMedia(value){if(typeof value==='string')return value.replace(/@asset:(asset\d+)/g,(_,id)=>embeddedMediaURL(id));if(Array.isArray(value))return value.map(resolveMedia);if(value&&typeof value==='object'){for(const key in value)if(key!=='assets')value[key]=resolveMedia(value[key])}return value}resolveMedia(DATA);
const KEY='llu-neuro-guide-v2';
let state={page:0,good:{},open:{},edits:{},notes:{},links:{},bookLabels:{}};
try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
let editing=false, activeKeyword='', activeBook='First Aid', liveBooks={};
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=DATA.pages;
const safeIndex=Number.isInteger(state.page)&&state.page>=0&&state.page<pages.length?state.page:0;state.page=safeIndex;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-status').textContent='Saved on this browser'}catch{$('#save-status').textContent='Storage full: export your progress'}}
function keywordify(html){const temp=document.createElement('div');temp.innerHTML=html;const walker=document.createTreeWalker(temp,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);const keys=Object.keys(DATA.references).sort((a,b)=>b.length-a.length);if(!keys.length)return html;const rx=new RegExp('(?<![\\p{L}\\p{N}_])('+keys.map(k=>k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')(?![\\p{L}\\p{N}_])','giu');for(const node of nodes){if(node.parentElement.closest('button,a,script,style'))continue;const text=node.textContent;if(!rx.test(text)){rx.lastIndex=0;continue}rx.lastIndex=0;const frag=document.createDocumentFragment();let from=0;for(const match of text.matchAll(rx)){frag.append(text.slice(from,match.index));const b=document.createElement('button');b.className='keyword';b.dataset.keyword=keys.find(k=>k.toLowerCase()===match[0].toLowerCase());b.textContent=match[0];frag.append(b);from=match.index+match[0].length}frag.append(text.slice(from));node.replaceWith(frag)}return temp.innerHTML}
function sourceLink(n,label='Cole review'){return `<a target="_blank" rel="noopener" href="../Core%20Sources/Neuro%20Board%20Review%20Sept%202026.pdf#page=${n}">${label} · PDF ${n}</a>`}
function renderNav(){const total=pages.flatMap(p=>p.blocks).length,done=pages.flatMap(p=>p.blocks).filter(b=>state.good[b.id]).length;$('#nav').innerHTML=pages.map((p,i)=>`<button class="nav-item ${i===state.page?'active':''}" data-page="${i}">${esc(p.title)}</button>`).join('')+'<div class="nav-appendices">COMPARISONS</div>'+DATA.comparison_sheets.map(s=>`<button class="nav-item" data-sheet="${s.id}">${esc(s.title)}</button>`).join('');$('#progress-text').textContent=`${done} / ${total} sections learned`;$('#progress-bar').style.width=`${done/total*100}%`;$('#word-budget').textContent=`${DATA.word_count.toLocaleString()} / 56,000 study words · ≈ ${Math.ceil(DATA.word_count/700)} page equivalents`;}
function figureMarkup(f,id){const source=f.source_url?`<a href="${f.source_url}" target="_blank" rel="noopener">${esc(f.source_label||'Lecture source')}</a>`:sourceLink(f.source_page);return `<figure class="inline-figure"><button class="figure-open" data-open-figure="${id}" aria-label="Read image in right panel: ${esc(f.caption)}"><img src="${f.src}" alt="${esc(f.caption)}" loading="lazy"></button><figcaption>${esc(f.caption)}${f.answer?' '+esc(f.answer):''} ${source}</figcaption></figure>`}
function chapterSourcesMarkup(p){const links=`<div class="source-links">${p.source_pages.map(n=>sourceLink(n)).join(' · ')}${p.lecture_sources?.length?'<div class="lecture-links">Lecture notes: '+sourceCitations(p.lecture_sources)+'</div>':''}</div>`;return `<details class="chapter-sources"><summary>Chapter sources</summary>${links}</details>`}
function blockSourcesMarkup(b){const links=`${b.professor_pages?.length?`<div class="block-source-links">Professor notes: ${b.professor_pages.map(n=>sourceLink(n)).join(' · ')}</div>`:''}${b.lecture_sources?.length?`<div class="block-source-links">Exact lecture notes: ${sourceCitations(b.lecture_sources)}</div>`:''}${b.external_sources?.length?`<div class="block-source-links">Supporting references: ${sourceCitations(b.external_sources)}</div>`:''}`;return links?`<details class="block-sources"><summary>Exact sources</summary>${links}</details>`:''}
function renderGuide(){renderNav();$('#guide').innerHTML=scopeOverviewMarkup()+scopePageEntries().map(({p,i},index,entries)=>`${topicHeadingMarkup(p,index,entries)}<article class="guide-chapter" id="page-${i}" data-week="${p.week||0}"><div class="chapter-intro"><h1>${esc(p.title)}</h1>${p.subtitle?`<p class="subtitle">${esc(p.subtitle)}</p>`:''}${chapterSourcesMarkup(p)}</div>${p.blocks.map(b=>`<section class="guide-section ${state.good[b.id]?'is-good':''}" data-block="${b.id}"><div class="block-head"><h2>${keywordify(esc(b.title))}</h2><button class="good-toggle" data-good="${b.id}" aria-pressed="${!!state.good[b.id]}">${state.good[b.id]?'Expand':'Mark learned'}</button></div><div class="compact-summary compact-skim" ${state.good[b.id]?'':'hidden'}>${blockSkimMarkup(b)}</div><div class="block-body" ${state.good[b.id]?'hidden':''}><div class="editable ${editing?'editing':''}" data-edit="${b.id}" contenteditable="${editing}" aria-label="Edit ${esc(b.title)}">${editing?(state.edits[b.id]||b.html):decorateReading(b.id,keywordify(state.edits[b.id]||b.html))}</div>${/<table[\s>]/i.test(state.edits[b.id]||b.html)?`<button class="anki-table-control" data-anki-table-block="${b.id}">Related cards for this table</button>`:''}${sectionFiguresMarkup(b)}${blockSourcesMarkup(b)}</div>${objectiveMarkup(b.id)}${questionSectionButton(b.id)}${missedQuestionsMarkup(b.id)}</section>`).join('')}<details class="margin-notes"><summary>Your notes on this section</summary><textarea data-note="${p.id}" aria-label="Notes for ${esc(p.title)}" placeholder="Add your notes…">${esc(state.notes[p.id]||'')}</textarea></details></article>`).join('');$('#edit-toggle').textContent=editing?'Finish editing':'Edit guide';$('#edit-toggle').setAttribute('aria-pressed',String(editing));updateQuestionLinks();refreshGuideLength()}

document.addEventListener('click',e=>{const n=e.target.closest('.nav-item[data-page]');if(n){state.page=+n.dataset.page;navigateView('guide');save();renderNav();$('#page-'+state.page).scrollIntoView({behavior:'instant',block:'start'})}const g=e.target.closest('[data-good]');if(g){const id=g.dataset.good;state.good[id]=!state.good[id];const section=g.closest('.guide-section');section.classList.toggle('is-good',state.good[id]);section.querySelector('.block-body').hidden=state.good[id];section.querySelector('.compact-summary').hidden=!state.good[id];g.textContent=state.good[id]?'Expand':'Mark learned';g.setAttribute('aria-pressed',String(state.good[id]));save();renderNav()}const k=e.target.closest('[data-keyword]');if(k&&!k.closest('.reading-highlight')&&!e.target.closest('.reading-highlight')){setReferenceContext(k.dataset.keyword,k);openRef(k.dataset.keyword)}});
document.addEventListener('toggle',e=>{if(e.target.matches('details[data-reveal]')){state.open[e.target.dataset.reveal]=e.target.open;save()}},true);
document.addEventListener('input',e=>{if(e.target.matches('[data-edit]')){state.edits[e.target.dataset.edit]=e.target.innerHTML;save()}if(e.target.matches('[data-note]')){state.notes[e.target.dataset.note]=e.target.value;save()}});
$('#edit-toggle').onclick=()=>{const y=window.scrollY;editing=!editing;render();window.scrollTo(0,y)};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({format:KEY,state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='neuro-study-progress.json';a.click();URL.revokeObjectURL(a.href)};
$('#import').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.format!==KEY||!d.state)throw Error('wrong format');state={...state,...d.state};state.page=Math.max(0,Math.min(pages.length-1,state.page|0));ensureScopePage();save();render();$('#save-status').textContent='Progress imported'}catch{$('#save-status').textContent='Could not import this progress file'}e.target.value=''};
const questionSections=pages.flatMap((p,i)=>p.blocks.map(b=>({id:b.id,title:b.title,page:p.title,pageIndex:i})));
state.questions||={};let questionActive='',questionView='all';
function qRecord(id){return state.questions[id]||{sections:[],tags:[],review:'not_queued',note:''}}
function qWrite(id){state.questions[id]||={sections:[],tags:[],review:'not_queued',note:''};return state.questions[id]}
function suggestedFor(q,id){return (q.suggested_sections||[]).some(s=>s.block_id===id)}
function questionSectionButton(id){const linked=DATA.questions.filter(q=>qRecord(q.id).sections.includes(id)).length;const suggestions=DATA.questions.filter(q=>suggestedFor(q,id)&&!qRecord(q.id).sections.includes(id)).length;return `<button class="question-section-button" data-section-questions="${id}" ${linked||suggestions?'':'hidden'}>Questions: ${linked} linked${suggestions?' · '+suggestions+' suggested':''}</button>`}
function updateQuestionLinks(){document.querySelectorAll('[data-section-questions]').forEach(b=>{const id=b.dataset.sectionQuestions;const linked=DATA.questions.filter(q=>qRecord(q.id).sections.includes(id)).length;const suggestions=DATA.questions.filter(q=>suggestedFor(q,id)&&!qRecord(q.id).sections.includes(id)).length;b.hidden=!(linked||suggestions);b.textContent=`Questions: ${linked} linked${suggestions?' · '+suggestions+' suggested':''}`});$('#queue-count').textContent=DATA.questions.filter(q=>scopeQuestion(q)&&qRecord(q.id).review==='later').length}
function openQuestions(section=''){navigateView('questions',{section});}
function initializeQuestions(section=''){initQuestionPage();questionView='all';$('#question-search').value='';$('#question-section-filter').value=section;questionActive='';renderQuestionList()}
function renderQuestionList(){if(!$('#question-list'))return;const term=$('#question-search').value.toLowerCase().trim(),section=$('#question-section-filter').value;let qs=DATA.questions.filter(q=>{const r=qRecord(q.id);return scopeQuestion(q)&&(questionView!=='later'||r.review==='later')&&(!section||r.sections.includes(section)||suggestedFor(q,section))&&(!term||[q.id,q.title,q.trigger,q.key_fact,...r.tags].join(' ').toLowerCase().includes(term))});if(!qs.some(q=>q.id===questionActive))questionActive=qs[0]?.id||'';$('#all-questions').setAttribute('aria-pressed',String(questionView==='all'));$('#queued-questions').setAttribute('aria-pressed',String(questionView==='later'));$('#question-count').textContent=`${qs.length} of ${DATA.questions.filter(scopeQuestion).length} questions${section?' · linked or suggested for this section':''}`;$('#question-list').innerHTML=qs.map(q=>{const r=qRecord(q.id);return `<button class="question-item ${q.id===questionActive?'active':''}" data-question-id="${q.id}">${esc(q.title)}<small>${esc(q.source_status)} in original appendix · ${r.review==='later'?'Review later':r.review==='reviewed'?'Reviewed':'Not queued'}${r.sections.length?' · '+r.sections.length+' section link'+(r.sections.length===1?'':'s'):''}</small></button>`}).join('')||'<p class="question-empty">No questions match. Use All questions to choose more, or change the filter.</p>';renderQuestionDetail()}
function renderQuestionDetail(){if(!$('#question-detail'))return;const q=DATA.questions.find(q=>q.id===questionActive);if(!q){$('#question-detail').innerHTML='<p class="question-empty">Choose a question to review.</p>';return}const r=qRecord(q.id);const suggested=(q.suggested_sections||[]).filter(s=>!r.sections.includes(s.block_id));const screenshot=questionImageUrl(q);$('#question-detail').innerHTML=`<div class="question-id">${esc(q.id)} · Original result: ${esc(q.source_status)}</div><h3>${esc(q.title.replace(/^(AMBOSS|UWorld) - /,''))}</h3><p class="question-trigger"><strong>Captured question context</strong><br>${esc(q.trigger)}</p><div class="auto-question-links"><strong>Tagged and linked for you</strong><p>${r.tags.length?r.tags.map(t=>`<span class="topic-chip">${esc(t)}</span>`).join(' '):esc(q.title.replace(/^(AMBOSS|UWorld)\s*[-–]\s*/,''))}</p><p>${r.sections.length?r.sections.map(id=>`<button data-jump-section="${id}">${esc(questionSections.find(b=>b.id===id)?.title||id)}</button>`).join(' '):'This question belongs to a later guide section; no match is forced into this opening draft.'}</p>${q.auto_rationale?`<p class="source-links">${esc(q.auto_rationale)}</p>`:''}</div><label class="review-note-label">What do you want to revisit?<textarea id="question-review-note" placeholder="Record the distinction you missed…">${esc(r.note)}</textarea></label><div class="queue-actions"><button id="queue-question" class="${r.review==='later'?'queued':''}">${r.review==='later'?'Remove from review later':'Review later'}</button><button id="reviewed-question" ${r.review==='reviewed'?'disabled':''}>${r.review==='reviewed'?'Marked reviewed':'Mark reviewed'}</button></div><div class="question-saved" role="status">${r.review==='later'?'Saved in your review-later queue':r.review==='reviewed'?'Reviewed; original result preserved':'Not in your review queue'}</div><details class="question-explanation"><summary>Show saved explanation and original screenshot</summary><div><p><strong>Key fact from appendix</strong><br>${esc(q.key_fact)}</p><p><strong>Original trap note</strong><br>${esc(q.trap)}</p><p class="question-tags-help">The original review screenshot may already show the answer. Some appendix trap notes are generic placeholders.</p><button class="source-image-button" data-source-image="${screenshot}" data-image-caption="${esc(q.title)}"><img loading="lazy" src="${screenshot}" alt="${esc(q.title)} original review screenshot"></button></div></details><p class="appendix-link"><a href="../Question%20Appendix/index.html" target="_blank" rel="noopener">Open the full original appendix</a></p>`;}
function persistQuestion(){save();updateQuestionLinks()}
function initQuestionPage(){ $('#question-section-filter').innerHTML='<option value="">All guide sections / unlinked</option>'+questionSections.filter(s=>!week8Scope()||scopePageSelected(pages[s.pageIndex])).map(s=>`<option value="${s.id}">Section ${s.pageIndex+1} · ${esc(s.title)}</option>`).join('');
$('#all-questions').onclick=()=>{questionView='all';renderQuestionList()};$('#queued-questions').onclick=()=>{questionView='later';renderQuestionList()};$('#question-search').oninput=renderQuestionList;$('#question-section-filter').onchange=renderQuestionList;}
document.addEventListener('click',e=>{const section=e.target.closest('[data-section-questions]');if(section)openQuestions(section.dataset.sectionQuestions);const q=e.target.closest('[data-question-id]');if(q){questionActive=q.dataset.questionId;renderQuestionList()}const accept=e.target.closest('[data-accept-question-link]');if(accept){const r=qWrite(questionActive);if(!r.sections.includes(accept.dataset.acceptQuestionLink))r.sections.push(accept.dataset.acceptQuestionLink);persistQuestion();renderQuestionList()}if(e.target.id==='queue-question'){const r=qWrite(questionActive);r.review=r.review==='later'?'not_queued':'later';persistQuestion();renderQuestionList()}if(e.target.id==='reviewed-question'){qWrite(questionActive).review='reviewed';persistQuestion();renderQuestionList()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-question-section]')){const r=qWrite(questionActive),id=e.target.dataset.questionSection;r.sections=e.target.checked?[...new Set([...r.sections,id])]:r.sections.filter(s=>s!==id);persistQuestion();renderQuestionList()}});
document.addEventListener('input',e=>{if(e.target.id==='question-tags'){qWrite(questionActive).tags=[...new Set(e.target.value.split(',').map(t=>t.trim()).filter(Boolean))];persistQuestion()}if(e.target.id==='question-review-note'){qWrite(questionActive).note=e.target.value;persistQuestion()}});
