// One saved image position per reading block, objective, or comparison row.
state.imagePositions ||= {};
let imageGallery=null;
function imagePosition(key,length){return Math.max(0,Math.min(length-1,Number(state.imagePositions[key])||0))}
function imageArrowMarkup(key,index,total,inline=false){return total>1?`<div class="section-image-nav" role="group" aria-label="Images for this section"><button ${inline?'data-inline-image-step':'data-gallery-step'}="-" data-image-group="${esc(key)}" aria-label="Previous section image" ${index===0?'disabled':''}>←</button><span>${index+1} / ${total} images</span><button ${inline?'data-inline-image-step':'data-gallery-step'}="+" data-image-group="${esc(key)}" aria-label="Next section image" ${index===total-1?'disabled':''}>→</button></div>`:''}
function sectionFiguresMarkup(block){const images=block.figures||[];if(!images.length)return '';const key='block:'+block.id,index=imagePosition(key,images.length);return `<div class="section-images" data-section-images="${esc(block.id)}">${imageArrowMarkup(key,index,images.length,true)}${figureMarkup(images[index],block.id+'-figure'+index)}</div>`}
function objectiveFiguresMarkup(objective,answer){const images=answer?.figures||[];if(!images.length)return '';const key='lo:'+objective.id,index=imagePosition(key,images.length),f=images[index];return `<div class="objective-image-gallery" data-objective-images="${esc(objective.id)}">${imageArrowMarkup(key,index,images.length,true)}<figure class="objective-image"><button data-lo-image="${esc(objective.id)}-${index}" data-objective-id="${esc(objective.id)}" data-image-index="${index}" data-image-src="${esc(f.src)}" data-image-caption="${esc(f.caption)}" aria-label="Open objective source image"><img loading="lazy" src="${esc(f.src)}" alt="${esc(f.caption)}"></button><figcaption>${esc(f.caption)} ${f.url?`<a href="${esc(String(f.url).split('#')[0])}${f.page?'#page='+f.page:''}" target="_blank" rel="noopener">${f.generated?'Diagram sources':'Exact source'}${f.page?' · PDF '+f.page:''}</a>`:''}</figcaption></figure></div>`}
function gallerySource(f){const url=f.source_url||f.url,page=f.source_page||f.page;return url?`<a href="${esc(String(url).split('#')[0])}${page?'#page='+page:''}" target="_blank" rel="noopener">${esc(f.source_label||f.label||'Exact source')}${page?' · PDF '+page:''}</a>`:f.source_page?sourceLink(f.source_page):''}
function openImageGallery(options){imageGallery=options;if(Number.isInteger(options.index))state.imagePositions[options.key]=options.index;renderImageGallery()}
function renderImageGallery(){if(!imageGallery?.images?.length)return;const g=imageGallery,index=imagePosition(g.key,g.images.length),f=g.images[index];state.imagePositions[g.key]=index;showSidePanel(g.title,`<section id="section-image-gallery" data-gallery-key="${esc(g.key)}">${imageArrowMarkup(g.key,index,g.images.length)}<p class="gallery-caption">${esc(f.caption||'')}</p><div class="panel-zoom"><button data-panel-zoom="-">−</button><span>Image zoom</span><button data-panel-zoom="+">+</button></div><div class="panel-media"><img src="${esc(f.src)}" alt="${esc(f.caption||'Section image')}"></div><p class="source-links">${gallerySource(f)}</p>${f.answer?`<p>${esc(f.answer)}</p>`:''}<p class="gallery-key-hint">← → move through this section’s images.</p></section>`);save()}
function refreshInlineImages(key){
 if(key.startsWith('block:')){const id=key.slice(6),block=pages.flatMap(p=>p.blocks).find(b=>b.id===id),target=document.querySelector(`[data-section-images="${CSS.escape(id)}"]`);if(block&&target)target.outerHTML=sectionFiguresMarkup(block)}
 else if(key.startsWith('lo:')){const id=key.slice(3),o=DATA.objectives.find(o=>o.id===id),target=document.querySelector(`[data-objective-images="${CSS.escape(id)}"]`);if(o&&target)target.outerHTML=objectiveFiguresMarkup(o,DATA.objective_answers[id])}
}
function stepSectionImages(key,delta){let images;if(key.startsWith('block:'))images=pages.flatMap(p=>p.blocks).find(b=>b.id===key.slice(6))?.figures;else if(key.startsWith('lo:'))images=DATA.objective_answers[key.slice(3)]?.figures;else if(imageGallery?.key===key)images=imageGallery.images;if(!images?.length)return;state.imagePositions[key]=Math.max(0,Math.min(images.length-1,imagePosition(key,images.length)+delta));save();refreshInlineImages(key);if(imageGallery?.key===key&&!$('#side-panel').hidden&&$('#section-image-gallery'))renderImageGallery()}
document.addEventListener('click',e=>{const arrow=e.target.closest('[data-gallery-step],[data-inline-image-step]');if(arrow)stepSectionImages(arrow.dataset.imageGroup,(arrow.dataset.galleryStep||arrow.dataset.inlineImageStep)==='+'?1:-1)});
document.addEventListener('keydown',e=>{if($('#side-panel').hidden||e.target.closest('input,textarea,select,[contenteditable=true]')||!window.getSelection()?.isCollapsed)return;if(!['ArrowLeft','ArrowRight'].includes(e.key))return;const delta=e.key==='ArrowRight'?1:-1;if($('#section-image-gallery')&&imageGallery){e.preventDefault();stepSectionImages(imageGallery.key,delta)}else if($('#side-content .anki-primary-media')&&typeof ankiContext!=='undefined'&&ankiContext){e.preventDefault();const media=ankiMediaResults();state.ankiMediaPosition[ankiContext.key]=Math.max(0,Math.min(media.length-1,(Number(state.ankiMediaPosition[ankiContext.key])||0)+delta));renderAnkiReference()}});
