let referenceOrigin=null;
let sideZoom=1,activeRef='',referenceBook='First Aid',rapidIndex=0,rapidRevealed=false,bookPanelActive=false;
// Keep a per-topic book and physical page selection. Highlight rectangles are
// stored in guide state by book + physical PDF page, so they survive navigation.
state.bookPageView||={};state.bookHighlights||={};
function bookViewKey(topic,book){return `${topic}::${book}`}
function getBookPageView(topic,book,pages){const key=bookViewKey(topic,book);let page=state.bookPageView[key];if(!pages.includes(page)){page=pages.find(p=>DATA.book_link_focus?.topics?.[topic]?.[book]?.[String(p)]?.spans?.length)||pages[0];if(page)state.bookPageView[key]=page}return page}
function showSidePanel(title,html,opts={}){const anchor=opts.anchor,opening=$('#side-panel').hidden,anchorTop=anchor?.isConnected?anchor.getBoundingClientRect().top:null;const priorScroll=$('#side-content').scrollTop;$('#side-title').textContent=title;$('#side-content').innerHTML=html;$('#side-panel').hidden=false;document.body.classList.add('with-panel');bookPanelActive=!!opts.bookPanel;if(!opts.keepZoom)sideZoom=1;$('#side-content').scrollTop=opts.keepScroll?priorScroll:0;if(opening&&anchorTop!==null&&anchorTop>=60&&anchorTop<window.innerHeight-35)requestAnimationFrame(()=>{if(anchor.isConnected)window.scrollBy({top:anchor.getBoundingClientRect().top-anchorTop,behavior:'instant'})})}
function setReferenceContext(topic,node){
 const passage=node?.closest?.('p,li,td')||node?.closest?.('[data-block],[data-objective-card],[data-sheet-row]');referenceOrigin={topic,text:passage?.textContent||'',blockId:node?.closest?.('[data-edit]')?.dataset.edit||'',element:node};
 const block=node?.closest?.('[data-block]'),row=node?.closest?.('[data-sheet-row]');
 let refs={professor_pages:[],lecture_sources:[]};
 if(block){const b=pages.flatMap(p=>p.blocks).find(b=>b.id===block.dataset.block);if(b)refs={professor_pages:b.professor_pages||[],lecture_sources:b.lecture_sources||[]}}
 else if(row){const r=DATA.comparison_sheets.find(s=>s.id===row.dataset.sheetRow)?.rows[Number(row.dataset.sheetIndex)];if(r)refs={professor_pages:r.source_pages||[],lecture_sources:r.lecture_sources||[]}}
 const objective=node?.closest?.('[data-objective-card]');if(objective)refs={professor_pages:[],lecture_sources:DATA.objective_answers[objective.dataset.objectiveCard]?.sources||[]};
 state.referenceSources||={};state.referenceSources[topic]=refs;
}
function referenceCourseSources(){const refs=state.referenceSources?.[activeRef];if(!refs)return '';return `<details class="reference-course-sources"><summary>Exact course slides / notes</summary><div class="source-links">${(refs.professor_pages||[]).map(p=>sourceLink(p)).join(' · ')} ${sourceCitations(refs.lecture_sources)}</div></details>`}
function sourceCitations(sources){return (sources||[]).map(s=>`<a href="${esc(s.url)}${s.page?'#page='+s.page:''}" target="_blank" rel="noopener">${esc(s.label||'Source')}${s.page?' · PDF '+s.page:''}</a>`).join(' · ')}
function openRef(key,book){if(typeof openStudyReference==='function')return openStudyReference(key,book);return openBookReference(key,book)}
function openBookReference(key,book){activeRef=key;const map=DATA.book_pages.keywords[key]||{};referenceBook=book||state.bookPageView[bookViewKey(key,'active-book')]||(map['First Aid']?.pages.length?'First Aid':'Pathoma');state.bookPageView[bookViewKey(key,'active-book')]=referenceBook;sideZoom=state.bookPageView[bookViewKey(key,'zoom')]||1;renderBookPanel();const savedScroll=state.bookPageView[bookViewKey(key,referenceBook+'-scroll')];requestAnimationFrame(()=>{if(savedScroll!==undefined)$('#side-content').scrollTop=savedScroll;else scrollToLinkedPassage()});save()}
function scrollToLinkedPassage(){const hit=$('#side-content .book-linked-passage');if(hit){const box=hit.getBoundingClientRect(),pane=$('#side-content');pane.scrollTop+=box.top-pane.getBoundingClientRect().top-90}}
// A saved guide highlight can jump directly to the matching topic in the book
// drawer; book/page and page-region highlights remain in state across jumps.
function openHighlightedTopic(topic,highlightId){openRef(topic,state.bookPageView[bookViewKey(topic,'active-book')]||(DATA.book_pages.keywords[topic]?.['First Aid']?.pages.length?'First Aid':'Pathoma'));if(highlightId){state.guideHighlightBookTopics||={};state.guideHighlightBookTopics[highlightId]=topic;save()}}
window.openHighlightedTopic=openHighlightedTopic;
window.refreshBookTextHighlights=()=>{if(bookPanelActive)renderBookPanel()};
function renderBookPanel(){const map=DATA.book_pages.keywords[activeRef]||{};const books=referenceBook==='Both'?['First Aid','Pathoma']:[referenceBook];const bookSetMarkup=books.map(bn=>{const book=DATA.book_pages.books[bn],ref=map[bn]||{pages:[],printed_pages:[],note:'No verified page for this term.'};const activePage=getBookPageView(activeRef,bn,ref.pages),pageIndex=Math.max(0,ref.pages.indexOf(activePage)),page=activePage||ref.pages[0],views=ref.pages.map(p=>`<button class="book-page-tab ${p===page?'selected':''}" data-book-name="${bn}" data-book-page="${p}" aria-label="Show ${bn} PDF page ${p}">PDF ${p}</button>`).join('');if(!page)return `<section class="book-reference-set"><h3>${esc(bn)}</h3><p class="ref-description"><strong>No named section located</strong> · ${esc(ref.note)}</p><p class="empty-ref">This edition does not have a verified dedicated section for this term.</p></section>`;return `<section class="book-reference-set"><h3>${referenceBook==='Both'?esc(bn):''}</h3><p class="panel-book-label">${esc(book.label)}</p><p class="ref-description"><strong>${ref.match==='related'?'Related section':'Direct reference'}</strong> · ${esc(ref.note)}</p><div class="book-page-navigation">${ref.pages.length>1?`<button data-book-name="${bn}" data-book-step="-" aria-label="Previous ${bn} reference page" ${pageIndex===0?'disabled':''}>‹</button><span>Page ${pageIndex+1} of ${ref.pages.length}</span><button data-book-name="${bn}" data-book-step="+" aria-label="Next ${bn} reference page" ${pageIndex===ref.pages.length-1?'disabled':''}>›</button>`:''}<a href="${book.url}#page=${page}" target="_blank" rel="noopener">Open full PDF · p. ${page}</a></div>${ref.pages.length>1?`<div class="book-page-tabs">${views}</div>`:''}<div class="panel-media book-page-media">${bookPageMarkup(bn,page,book,ref)}</div></section>`}).join('');const toggle=`<div class="book-mark-toolbar"><button id="book-mark-toggle" aria-pressed="${bookMarkMode}">${bookMarkMode?'Cancel page marking':'Mark a page region'}</button><span>Drag across a diagram or region. For text, select it and press H.</span></div>`;showSidePanel(activeRef,`${typeof referenceTabsMarkup==='function'?referenceTabsMarkup('books'):''}${toggle}<div class="panel-zoom"><button data-panel-zoom="-">−</button><span>Page zoom</span><button data-panel-zoom="+">+</button></div>${referenceCourseSources()}<p class="book-focus-legend"><b>Linked passage</b> · <span class="saved-mark">Your saved highlights</span> <button data-book-find-passage>Find passage</button></p>${bookSetMarkup}`,{keepZoom:true,keepScroll:true,bookPanel:true,anchor:referenceOrigin?.element});applySideZoom();setBookMarkMode(bookMarkMode);}
function comparisonMarkup(sheetId=null){const sheets=sheetId?DATA.comparison_sheets.filter(s=>s.id===sheetId):DATA.comparison_sheets;return `<section class="comparison-appendix" id="comparisons"><div class="eyebrow">COMPARISON SHEETS · OUTSIDE THE WORD LIMIT</div><h1>${sheetId?esc(sheets[0]?.title||'Comparison'):'Drugs, bugs & pathology'}</h1>${sheets.map(s=>`<section class="comparison-sheet" id="sheet-${s.id}">${sheetId?'':`<h2>${esc(s.title)}</h2>`}<p class="ref-description">${esc(s.scope_note)}</p><label class="sheet-search">Filter ${esc(s.title.toLowerCase())}<input type="search" data-sheet-filter="${s.id}" placeholder="Name, mechanism, finding…"></label><div class="table-scroll"><table><thead><tr>${s.columns.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Source</th></tr></thead><tbody>${s.rows.map((row,ri)=>({row,ri})).filter(({ri})=>scopeRow(s.id,ri)).map(({row,ri})=>`<tr data-sheet-row="${s.id}" data-sheet-index="${ri}">${row.cells.map((c,ci)=>`<td><div class="editable comparison-cell" data-edit="sheet-${s.id}-${ri}-${ci}" contenteditable="false">${decorateReading(`sheet-${s.id}-${ri}-${ci}`,keywordify(c))}</div>${s.id==='pathology'&&ci===0?pathImages(ri):''}</td>`).join('')}<td class="sheet-sources"><button data-anki-row aria-label="Related Anki cards for ${esc(ankiPlain(row.cells[0]))}">Related cards</button>${(row.source_pages||[]).map(p=>sourceLink(p)).join(' · ')}${sourceCitations(row.lecture_sources)}${(row.external_sources||[]).map(x=>`<br><a href="${x.url}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join('')}</td></tr>`).join('')}</tbody></table></div></section>`).join('')}</section>`}
function openFigure(id){for(const p of pages)for(const b of p.blocks){const index=(b.figures||[]).findIndex((f,j)=>b.id+'-figure'+j===id);if(index>=0){openImageGallery({key:'block:'+b.id,title:b.title,images:b.figures,index});return}}}
state.rapidPathology||={};
function openRapid(){rapidIndex=0;rapidRevealed=false;renderRapid()}
function renderRapid(){const cards=scopeRapidCards(),card=cards[rapidIndex],known=cards.filter(c=>state.rapidPathology[c.id]==='known').length;showSidePanel('Rapid pathology review',`<section id="rapid-card"><p class="rapid-progress">${rapidIndex+1} / ${cards.length} · ${known} marked known</p><h3>${esc(card.title)}</h3><p class="rapid-prompt">${esc(card.prompt)}</p>${rapidRevealed?`<div class="rapid-answer">${keywordify(card.answer_html)}<div class="source-links">${sourceCitations(card.sources)}</div></div>`:'<p class="rapid-hint">Say the answer, then reveal.</p>'}<div class="rapid-actions"><button id="rapid-reveal">${rapidRevealed?'Hide answer':'Reveal · Space'}</button><button id="rapid-prev">← Previous</button><button id="rapid-next">Next →</button></div><div class="rapid-actions"><button data-rapid-grade="again">Again</button><button data-rapid-grade="known">Got it</button></div><p class="rapid-hint">Space: reveal / next. ← →: previous / next. These marks stay in the guide; your Anki deck is unchanged.</p></section>`)}
function stepRapid(delta){rapidIndex=(rapidIndex+delta+scopeRapidCards().length)%scopeRapidCards().length;rapidRevealed=false;renderRapid()}
$('#close-side').onclick=()=>{$('#side-panel').hidden=true;document.body.classList.remove('with-panel')};$('#rapid-button').onclick=openRapid;
document.addEventListener('click',e=>{const book=e.target.closest('[data-panel-book]');if(book){referenceBook=book.dataset.panelBook;state.bookPageView[bookViewKey(activeRef,'active-book')]=referenceBook;save();if(typeof rememberReferenceBook==='function')rememberReferenceBook();bookMarkMode=false;renderBookPanel()}const figure=e.target.closest('[data-open-figure]');if(figure)openFigure(figure.dataset.openFigure);const sheet=e.target.closest('[data-sheet]');if(sheet)$('#sheet-'+sheet.dataset.sheet).scrollIntoView({behavior:'smooth',block:'start'});const zoom=e.target.closest('[data-panel-zoom]');if(zoom){sideZoom=Math.max(.6,Math.min(3,sideZoom+(zoom.dataset.panelZoom==='+'?.25:-.25)));if($('#side-content').querySelector('.book-page-canvas')){applySideZoom();state.bookPageView[bookViewKey(activeRef,'zoom')]=sideZoom;save();}else $('#side-content').querySelectorAll('.panel-media img').forEach(im=>{im.style.width=(sideZoom*100)+'%';im.style.maxWidth='none'})}if(e.target.id==='rapid-reveal'){rapidRevealed=!rapidRevealed;renderRapid()}if(e.target.id==='rapid-next')stepRapid(1);if(e.target.id==='rapid-prev')stepRapid(-1);const grade=e.target.closest('[data-rapid-grade]');if(grade){state.rapidPathology[scopeRapidCards()[rapidIndex].id]=grade.dataset.rapidGrade;save();stepRapid(1)}});
document.addEventListener('input',e=>{if(e.target.matches('[data-sheet-filter]')){const term=e.target.value.toLowerCase();document.querySelectorAll(`[data-sheet-row="${e.target.dataset.sheetFilter}"]`).forEach(tr=>tr.hidden=!tr.textContent.toLowerCase().includes(term))}});
document.addEventListener('keydown',e=>{if($('#side-panel').hidden||!$('#rapid-card')||e.target.closest('input,textarea,select,[contenteditable="true"]')||document.querySelector('dialog[open]'))return;if(e.key===' '){e.preventDefault();if(rapidRevealed)stepRapid(1);else{rapidRevealed=true;renderRapid()}}if(e.key==='ArrowRight'){e.preventDefault();stepRapid(1)}if(e.key==='ArrowLeft'){e.preventDefault();stepRapid(-1)}});

$('#side-content').addEventListener('scroll',()=>{if(bookPanelActive){state.bookPageView[bookViewKey(activeRef,referenceBook+'-scroll')]=$('#side-content').scrollTop;save()}},{passive:true});

document.addEventListener('click',e=>{if(e.target.closest('[data-book-find-passage]'))scrollToLinkedPassage()});
